import { LightShadowType } from "../common/constants/LightShadowType";
import { StyleType } from "../common/constants/StyleType";
import { WeaponType } from "../common/constants/WeaponType";
import { Unit } from "../common/types/Unit";

const units: Unit[] = (() => {
  const _units: Unit[] = [
    {
      weapon: WeaponType.Lod,
      name: "マリエル",
      namekana: "マリエル",
      lightShadow: LightShadowType.Light,
      className: "ハイエロファント",
      styleType: StyleType.NS,
      hp: 3444,
      mp: 655,
      power: 211,
      endure: 190,
      luck: 180,
      intelligence: 182,
      split: 190,
      speed: 202,
    },
    {
      weapon: WeaponType.Fist,
      name: "ハーディー",
      namekana: "ハーディー",
      lightShadow: LightShadowType.Shadow,
      className: "グレイハウンド",
      styleType: StyleType.NS,
      hp: 3444,
      mp: 655,
      power: 211,
      endure: 190,
      luck: 180,
      intelligence: 182,
      split: 190,
      speed: 202,
    },
    {
      weapon: WeaponType.Katana,
      name: "イスカ",
      namekana: "イスカ",
      lightShadow: LightShadowType.Light,
      className: "アドミラル",
      styleType: StyleType.NS,
      hp: 3444,
      mp: 655,
      power: 211,
      endure: 190,
      luck: 180,
      intelligence: 182,
      split: 190,
      speed: 202,
    },
    {
      weapon: WeaponType.Fist,
      name: "ロキド",
      namekana: "ロキド",
      lightShadow: LightShadowType.Light,
      className: "フィエルテベート",
      styleType: StyleType.AS,
      hp: 3444,
      mp: 655,
      power: 211,
      endure: 190,
      luck: 180,
      intelligence: 182,
      split: 190,
      speed: 202,
    },
    {
      weapon: WeaponType.Sward,
      name: "イスカ",
      namekana: "イスカ",
      lightShadow: LightShadowType.Light,
      className: "ユースティティア",
      styleType: StyleType.ES,
      hp: 3444,
      mp: 655,
      power: 211,
      endure: 190,
      luck: 180,
      intelligence: 182,
      split: 190,
      speed: 202,
    },
    {
      weapon: WeaponType.Katana,
      name: "黒衣の刀使い",
      namekana: "コクイノカタナツカイ",
      lightShadow: LightShadowType.Shadow,
      className: "ユダ",
      styleType: StyleType.NS,
      hp: 3444,
      mp: 655,
      power: 211,
      endure: 190,
      luck: 180,
      intelligence: 182,
      split: 190,
      speed: 202,
    },
    {
      weapon: WeaponType.Lod,
      name: "デュナリス",
      namekana: "デュナリス",
      lightShadow: LightShadowType.Shadow,
      className: "ソウルブリンガー",
      styleType: StyleType.NS,
      hp: 3444,
      mp: 655,
      power: 211,
      endure: 190,
      luck: 180,
      intelligence: 182,
      split: 190,
      speed: 202,
    },
  ];

  return _units
    .sort((a, b) => a.namekana >= b.namekana ? 1 : -1)
    .sort((a, b) => a.weapon >= b.weapon ? 1 : -1);
})();

export function fetchUnits() {
  return units;
}
